package surfsara.java.constants;

import java.util.Arrays;
import java.util.HashSet;
import java.util.List;

import org.apache.hadoop.thirdparty.guava.common.collect.Sets;

public class Terror {

	public HashSet<String> getTerrorWords() {
		return Sets.newHashSet("AL Qaeda", "Anti-Semitism", "Fundamentalist",
				"Freedom Fighter", "Account", "Acid", "Advance", "Aerial",
				"Agency", "Aggression", "Aggressor", "Agitator", "Aim",
				"Aircraft", "Airfield", "Airplane", "Airport", "Alarm",
				"Alert", "Alliance", "Allies", "Ambush", "Ammunition",
				"Anarchy", "Anguish", "Annihilate", "Apartheid", "Appeasement",
				"Armament", "Armory", "Arms", "Arsenal", "Artillery", "Ashore",
				"Assassin", "Assassinate", "Assault", "Atrocity", "Attack",
				"Attrition", "Authority", "Automatic", "Barrage", "Barricade",
				"Battalion", "Battle", "Battlefield", "Belligerent", "Betray",
				"Blast", "Blindside", "Blood(y)", "Bloodletting", "Blow up",
				"Bomb", "Bombardment", "Booby trap", "Breach", "Brutal",
				"Brutality", "Bullet", "Bulletproof", "Bunker", "Burn",
				"Burning", "Bury", "Cadaver", "Camouflage", "Campaign",
				"Captive", "Captive", "Capture", "Careen", "Cargo", "Carnage",
				"Carrier", "Casualties", "Cataclysm", "Cautionary", "Cautious",
				"Chaos", "Charge", "Charred", "Checkpoint", "Chief", "Chopper",
				"Civilian", "Clamor", "Clandestine", "Clash", "Coalition",
				"Collapse", "Combat", "Command", "Commandos", "Compassion",
				"Compliance", "Concentration", "Concussion", "Conflagration",
				"Conflict", "Confrontation(al)", "Confusion", "Conquer",
				"Consequences", "Consolidate", "Conspiracy", "Conspire",
				"Control", "Convoy", "Coordinate", "Coordinates", "Corps",
				"Corpse", "Counterattack", "Countermand", "Courageous",
				"Crisis", "Cross-hairs", "Culpability", "Damage", "Danger",
				"Dangerous", "Dash", "Dead", "Deadly", "Death", "Debacle",
				"Debris", "Decline", "Defect", "Defend", "Defense",
				"Defensive", "Defiant", "Demolish", "Demoralization", "Deploy",
				"Desert", "Despot", "Destroy", "Destruction", "Detect",
				"Detection", "Detonate", "Devastation", "Device", "Dictator",
				"Die", "Disarmament", "Disarray", "Disaster", "Disastrous",
				"Discipline", "Disease", "Dismantle", "Dispatch", "Disperse",
				"Dispute", "Disruption", "Dissonance", "Dominate", "Doom",
				"Downfall", "Drama", "Dread", "Drone", "Duck", "Duty",
				"Encounter", "Endurance", "Enemy", "Enforcement", "Engagement",
				"Epithet", "Escalation", "Escape", "Evacuate", "Evacuee",
				"Excess", "Execute", "Execution", "Exercise", "Expectations",
				"Explode", "Exploitation", "Explosion", "Explosive", "Expunge",
				"Extremism", "Extremist", "Faction", "Fanatic", "Fatal",
				"Fear", "Fearless", "Ferment", "Ferocious", "Feud", "Fierce",
				"Fiery", "Fight", "Fighter", "Flank", "Flee", "Flight",
				"Force", "Forceful", "Fortification", "Foxhole", "Fray",
				"Frenzy", "Fright", "Front lines", "Fuel", "Fugitive",
				"Furtive", "Garrison", "Gas", "Generator", "Genocide",
				"Germ warfare", "Government", "Grave", "Grenade", "Grievous",
				"Groans", "Guard", "Guerrillas", "Guided bombs", "Guns",
				"Gunship", "Hammering", "Harsh", "Hatch", "Hate", "Hatred",
				"Hazard", "Helicopter", "Heroic", "Heroism", "Hide", "Hijack",
				"Hijacker", "Hit", "Hit-and-run", "Holocaust", "Horrific",
				"Horses", "Hostile", "Hostility", "Howitzer", "Ignite",
				"Impact", "Improvise", "Incident", "Incite",
				"Incontrovertible", "Indoctrination", "Infantry", "Inferred",
				"Infiltrate", "Infidel", "Inflame", "Informant", "Injuries",
				"Instructions", "Insurgent", "Insurrection", "Intelligence",
				"Intense", "Intercept", "Interdiction", "International",
				"Interrogation", "Intervene", "Intimidate", "Invasion",
				"Investigate", "Investigations", "Involvement", "Ire", "Jeer",
				"Jets", "Join", "Jihad", "Keening", "Kidnap", "Kill", "Knives",
				"Knock-out", "Koran", "Lamentation", "Land mines",
				"Laser-activated", "Launch", "Launcher", "Legacy", "Liaison",
				"Liberation", "Liberators", "Links to", "Loathsome", "Loyalty",
				"Machine guns", "Machines", "Maim", "Malevolent", "Malicious",
				"Maraud", "March", "Massacre", "Mayhem", "Megalomania",
				"Menace", "Method", "Militancy", "Militant", "Militaristic",
				"Military", "Militia", "Mines", "Missile", "Mission",
				"Mistreatment", "Mobile", "Mobilization", "Momentum",
				"Mortars", "Munitions", "Murder", "Muscle", "Nationalist",
				"Negotiation", "Neutralize", "Nightmare", "Nitrate",
				"Notorious", "Offensive", "Officials", "Onerous", "Operation",
				"Opposition", "Order", "Outbreak", "Overrun", "Overthrow",
				"Pacify", "Paramedics", "Partisan", "Patriot", "Patriotism",
				"Patrol", "Penetration", "Performance", "Persecute", "Petrify",
				"Photos", "Pilot", "Pistol", "Planes", "Platoon", "Plunder",
				"Position", "Post-traumatic", "Potent", "Pound", "Powder",
				"Power", "Powerful", "Preemptive", "Premeditate", "Prey",
				"Prison", "Prisoner", "Proliferation", "Provocation", "Prowl",
				"Pugnacious", "Pulverize", "Quail", "Quarrel", "Quell",
				"Quiver", "Radiation", "Radical", "Rage", "Rally", "Ravage",
				"Ravish", "Reaction", "Readiness", "Rebel", "Rebellion",
				"Reconnaissance", "Recovery", "Recruitment", "Refugee",
				"Regime", "Regiment", "Reinforcements", "Relentless",
				"Reparation", "Reprisal", "Reputation", "Rescue", "Resistance",
				"Retaliation", "Retreat", "Retribution", "Revenge",
				"Revolution", "Ricochet", "Rifle", "Rift", "Rival", "Rocket",
				"Rot", "Rounds", "Rule", "Ruthless", "Sabotage", "Sacrifice",
				"Salvage", "Sanction", "Savage", "Scare", "Score", "Scramble",
				"Screening", "Secrecy", "Secret", "Security", "Sedition",
				"Seize", "Seizure", "Sensor", "Setback", "Shelling", "Shells",
				"Shock", "Shoot", "Shot", "Showdown", "Siege", "Skirmish",
				"Slaughter", "Smuggle", "Soldier", "Special-ops",
				"Specialized", "Spokesman", "Spotter", "Spy", "Spy satellite",
				"Squad", "Stash", "Stealth", "Storage", "Storm", "Straggler",
				"Strangle", "Strategic", "Strategist", "Strategy", "Strife",
				"Strike", "Strip", "Stronghold", "Struggle", "Submarine",
				"Subversive", "Suffering", "Superstition", "Supplies",
				"Support", "Suppression", "Surprise", "Surrender", "Survival",
				"Survivor", "Suspect", "Tactics", "Tank", "Target", "Tension",
				"Terrain", "Terror", "Terrorism", "Terrorist", "Terrorize",
				"Threat", "Threaten", "Thwart", "Topple", "Torah", "Torch",
				"Torpedo", "Tourniquet", "Tragic", "Training", "Trample",
				"Transportation", "Trap", "Trauma", "Treachery", "Trench",
				"Trigger", "Triumph", "Turbulent", "Unbelievable",
				"Unconventional", "Unexpected", "Uniform", "Unify", "Unit",
				"Unite", "Unleash", "Uprising", "Urgency", "Vanguard",
				"Vanish", "Vehicle", "Vehicular", "Vendetta", "Venomous",
				"Veteran", "Vicious", "Victory", "Vile", "Vilify", "Violation",
				"Violence", "Virulence", "Vital", "Vitriol", "Vociferous",
				"Void", "Vow", "Vulnerability", "Wage", "War", "Warheads",
				"Warnings", "Warplane", "Warrant", "Warrior", "Watch list",
				"Watchdog", "Watchful", "Weapon", "Well-trained", "Whiz",
				"Wince", "Wisdom", "Worldwide", "Wounds", "Wreckage", "X-ray",
				"Yearn", "Yelling", "Zeal", "Zealot", "Zionism", "Zigzag",
				"Zone", "weapon", "bomb", "criminal", "delinquency",
				"smuggling", "smuggler", "explosion", "reporter", "fire",
				"newscast", "police", "strike", "kidnapping", "clash", "press",
				"slaughter", "citizen", "dictatorship", "speech", "government",
				"leader", "law", "demonstration", "minister", "movement",
				"income", "underclass", "tax", "illiteracy", "discrimination",
				"hunger", "war", "immigration", "pollution", "malnutrition",
				"controversy", "poverty", "prejudice", "racism", "rape",
				"terrorism", "alarming", "starving", "apathetic", "guilty",
				"disappointed", "excluded", "undecided", "controversial",
				"scant", "abdication", "Autounfall", "ambassador",
				"xenophobia", "army", "soldier", "arrest", "avalanche",
				"brain", "brain-damaged", "brain-dead", "business, economy",
				"CDU", "chancellor", "federal  chancellor", "confrontation",
				"consent", "crash", "crashed", "currency", "custody", "arrest",
				"detention", "execution", "divorce", "earthquake", "education",
				"election", "embassy", "emergency", "espionage", "execution",
				"explosive", "explosion", "foreigner", "gasoline", "petrol",
				"government", "headline", "hypocrisy", "immigrant",
				"immigration", "insurance", "king", "kingdom", "landslide",
				"mudslide", "law", "limit", "limitation", "parliament", "pass",
				"passage ", "pension", "pensioner", "politics", "poll",
				"president", "rape", "recession", "slowdown", "doldrums",
				"receive ", "recover", "salvage", "rescue", "representative",
				"resignation", "restriction", "rightwing ", "rightwing",
				"violence", "rightist", "rightwinger", "robber", "robbery",
				"royal", "senate", "senator", "sentence", "condemn", "pass",
				"judgment", "slave", "soldier", "SPD", "sports ", "spy",
				"storm", "study ", "threat", "threaten", "thunderstorm",
				"tsunami", "unemployment", "union", "victim", "violence",
				"warrant", "revolutionary", "militant", "radical",
				"subversive", "thug", "activist", "desperado", "rebel",
				"rioter", "tough", "anarchist", "bomber", "crook", "gangster",
				"goon", "guerrillan", "bushfighter", "hood", "hoodlum",
				"hooligan", "incendiary", "insurgent", "protestor", "ruffian",
				"Mafioso", "baddy", "criminal", "demonstrator", "felon",
				"gunman", "knave", "larrikin", "mobster", "racketeer",
				"roughneck", "aggressive", "alarmist", "apache", "arsonist",
				"assassin", "baddie", "blackguard", "brutal", "brutish",
				"bullying", "convict", "culprit", "cutthroat", "enemy",
				"guerilla", "gunsel", "heavy", "high-pressure", "hijacker",
				"abductor", "insurrectionary", "insurrectionist", "irregular",
				"killer", "lawbreaker", "malefactor", "miscreant", "mug",
				"mugger", "murderer", "mutineer", "nihilist", "offender",
				"outlaw", "p'hansigar", "partisan", "partizan", "plug-ugly",
				"revolutionist", "robber", "rough", "rowdy", "saboteur",
				"sansculotte", "sansculottist", "scoundrel", "torpedo",
				"villain", "wrongdoer", "yob", "yobbo");
	}

	public List<String> getStopWords() {
		return Arrays
				.asList("about", "above", "across", "after", "again",
						"against", "all", "almost", "alone", "along",
						"already", "also", "although", "always", "among", "an",
						"and", "another", "any", "anybody", "anyone",
						"anything", "anywhere", "are", "area", "areas",
						"around", "as", "ask", "asked", "asking", "asks", "at",
						"away", "b", "back", "backed", "backing", "backs",
						"be", "became", "because", "become", "becomes", "been",
						"before", "began", "behind", "being", "beings", "best",
						"better", "between", "big", "both", "but", "by", "c",
						"came", "can", "cannot", "case", "cases", "certain",
						"certainly", "clear", "clearly", "come", "could", "d",
						"did", "differ", "different", "differently", "do",
						"does", "done", "dont", "down", "down", "downed",
						"downing", "downs", "during", "e", "each", "early",
						"either", "end", "ended", "ending", "ends", "enough",
						"even", "evenly", "ever", "every", "everybody",
						"everyone", "everything", "everywhere", "f", "far",
						"felt", "few", "find", "finds", "first", "for", "four",
						"from", "full", "fully", "further", "furthered",
						"furthering", "furthers", "g", "gave", "generally",
						"get", "gets", "give", "given", "gives", "go", "going",
						"got", "h", "had", "has", "have", "having", "he",
						"her", "here", "herself", "high", "higher", "highest",
						"him", "himself", "his", "how", "however", "i", "if",
						"in", "into", "is", "it", "its", "itself", "j", "just",
						"k", "keep", "keeps", "kind", "knew", "know", "known",
						"knows", "l", "large", "largely", "last", "later",
						"latest", "least", "less", "let", "lets", "like",
						"likely", "m", "made", "make", "making", "man", "many",
						"may", "me", "member", "members", "men", "might",
						"more", "most", "mostly", "mr", "mrs", "much", "must",
						"my", "myself", "n", "never", "new", "new", "newer",
						"newest", "next", "no", "nobody", "non", "noone",
						"not", "nothing", "now", "nowhere", "o", "of", "off",
						"often", "old", "older", "oldest", "on", "once", "one",
						"only", "or", "other", "others", "our", "out", "over",
						"p", "per", "perhaps", "put", "puts", "q", "quite",
						"r", "rather", "really", "right", "s", "said", "same",
						"saw", "say", "says", "see", "seem", "seemed",
						"seeming", "seems", "sees", "several", "shall",
						"Sharia Law", "she", "should", "show", "showed",
						"showing", "shows", "side", "sides", "since", "so",
						"some", "somebody", "someone", "something",
						"somewhere", "still", "still", "such", "sure", "t",
						"take", "taken", "than", "that", "the", "their",
						"them", "then", "there", "therefore", "these", "they",
						"thing", "things", "think", "thinks", "this", "those",
						"though", "thought", "thoughts", "three", "through",
						"thus", "to", "today", "together", "too", "took",
						"toward", "turn", "turned", "turning", "turns", "two",
						"u", "under", "until", "up", "upon", "us", "use",
						"used", "uses", "v", "very", "w", "want", "wanted",
						"wanting", "wants", "was", "way", "ways", "we", "well",
						"wells", "went", "were", "what", "when", "where",
						"whether", "which", "while", "who", "whole", "whose",
						"why", "will", "with", "within", "without", "work",
						"worked", "working", "works", "would", "x", "y",
						"year", "years", "yet", "you", "young", "younger",
						"youngest", "your", "yours", "z",

						"www", "com", "http", "site", "using", "page", "web",
						"website", "de", "sites", "en", "am", "co", "own",
						"please", "feed", "rss", "below", "click", "em",
						"href", "strong", "title", "abbr", "cite", "strike",
						"del",

						"home", "business", "save", "day", "online", "free",
						"life", "little", "looking", "look", "able", "getting",
						"spend", "doing", "real", "feel", "try", "time",
						"people", "lot", "help");
	}

	public HashSet<String> getEnglishWords() {
		return Sets.newHashSet("about", "above", "across", "after", "again",
				"against", "all", "almost", "alone", "along", "already",
				"also", "although", "always", "among", "and", "another", "any",
				"anybody", "anyone", "anything", "anywhere", "are", "area",
				"areas", "around", "ask", "asked", "asking", "asks", "away",
				"back", "backed", "backing", "backs", "became", "because",
				"become", "becomes", "been", "before", "began", "behind",
				"being", "beings", "best", "better", "between", "big", "both",
				"but", "came", "can", "cannot", "case", "cases", "certain",
				"certainly", "clear", "clearly", "come", "could", "did",
				"differ", "different", "differently", "does", "done", "down",
				"down", "downed", "downing", "downs", "during", "each",
				"early", "either", "end", "ended", "ending", "ends", "enough",
				"even", "evenly", "ever", "every", "everybody", "everyone",
				"everything", "everywhere", "face", "faces", "fact", "facts",
				"far", "felt", "few", "find", "finds", "first", "for", "four",
				"from", "full", "fully", "further", "furthered", "furthering",
				"furthers", "gave", "general", "generally", "get", "gets",
				"give", "given", "gives", "going", "good", "goods", "got",
				"great", "greater", "greatest", "group", "grouped", "grouping",
				"groups", "had", "has", "have", "having", "her", "here",
				"herself", "high", "high", "high", "higher", "highest", "him",
				"himself", "his", "how", "however", "important", "interest",
				"interested", "interesting", "interests", "into", "its",
				"itself", "just", "keep", "keeps", "kind", "knew", "know",
				"known", "knows", "large", "largely", "last", "later",
				"latest", "least", "less", "let", "lets", "like", "likely",
				"long", "longer", "longest", "made", "make", "making", "man",
				"many", "may", "member", "members", "men", "might", "more",
				"most", "mostly", "much", "must", "myself", "necessary",
				"need", "needed", "needing", "needs", "never", "new", "newer",
				"newest", "next", "nobody", "noone", "not", "nothing", "now",
				"nowhere", "number", "numbers", "off", "often", "old", "older",
				"oldest", "once", "one", "only", "open", "opened", "opening",
				"opens", "order", "ordered", "ordering", "orders", "other",
				"others", "our", "out", "over", "part", "parted", "parting",
				"parts", "perhaps", "place", "places", "point", "pointed",
				"pointing", "points", "possible", "present", "presented",
				"presenting", "presents", "problem", "problems", "puts",
				"quite", "rather", "really", "right", "right", "room", "rooms",
				"said", "same", "saw", "say", "says", "second", "seconds",
				"see", "seem", "seemed", "seeming", "seems", "sees", "several",
				"shall", "she", "should", "show", "showed", "showing", "shows",
				"side", "sides", "since", "small", "smaller", "smallest", "so",
				"some", "somebody", "someone", "something", "somewhere",
				"state", "states", "still", "still", "such", "sure", "take",
				"taken", "than", "that", "the", "their", "them", "then",
				"there", "therefore", "these", "they", "thing", "things",
				"think", "thinks", "this", "those", "though", "thought",
				"thoughts", "three", "through", "thus", "today", "together",
				"too", "took", "toward", "turn", "turned", "turning", "turns",
				"two", "under", "until", "upon", "use", "used", "uses", "very",
				"want", "wanted", "wanting", "wants", "was", "way", "ways",
				"well", "wells", "went", "were", "what", "when", "where",
				"whether", "which", "while", "who", "whole", "whose", "why",
				"will", "with", "within", "without", "work", "worked",
				"working", "works", "would", "year", "years", "yet", "you",
				"young", "younger", "youngest", "your", "yours");

	}
}